auth:
  database: studiodb
  password: password
  username: access
global:
  imagePullSecrets:
    - name: dockerhub-creds
primary:
  initdb:
    scriptsConfigMap: db-init-configmap
  persistence:
    enabled: false
    size: 5Gi
    storageClass: standard
  service:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: postgres.example.com
    ports:
      postgresql: "5432"
    type: LoadBalancer
