packages:
  - components/*
  - modules

overrides:
  webpack-dev-server@<=5.2.0: '>=5.2.1'
  tmp@<=0.2.3: '>=0.2.4'
  lodash@>=4.0.0 <=4.17.22: '>=4.17.23'
  qs@>=6.7.0 <=6.14.1: '>=6.14.2'
  axios@>=1.0.0 <=1.13.4: '>=1.13.5'
  ajv@<6.14.0: '>=6.14.0'
  ajv@>=7.0.0-alpha.0 <8.18.0: '>=8.18.0'
  bn.js@<4.12.3: '>=4.12.3'
  minimatch@<3.1.3: '>=3.1.3'
  minimatch@>=9.0.0 <9.0.6: '>=9.0.6'
  basic-ftp@<5.2.0: '>=5.2.0'
