apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "management-server.serviceAccountName" . }}
  labels:
    application: skupperx
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
  - patch
- apiGroups:
  - cert-manager.io
  resources:
  - issuers
  - certificates
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    application: skupperx
  name: {{ include "management-server.serviceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "management-server.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "management-server.serviceAccountName" . }}