{{ if index .Values "cert-manager" "enabled" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "management-server.fullname" . }}-wait-deployments
  namespace: {{ index .Values "cert-manager" "namespace" }}
  labels:
    {{- include "management-server.labels" . | nindent 4 }}
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "management-server.fullname" . }}-wait-deployments
  namespace: {{ index .Values "cert-manager" "namespace" }}
  labels:
    {{- include "management-server.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "management-server.fullname" . }}-wait-deployments
subjects:
  - kind: ServiceAccount
    name: {{ include "management-server.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "management-server.fullname" . }}-wait-webhook-config
  labels:
    {{- include "management-server.labels" . | nindent 4 }}
rules:
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["validatingwebhookconfigurations"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "management-server.fullname" . }}-wait-webhook-config
  labels:
    {{- include "management-server.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "management-server.fullname" . }}-wait-webhook-config
subjects:
  - kind: ServiceAccount
    name: {{ include "management-server.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{ end }}
