{{- if eq .Values.role "app" }}
apiVersion: skupper.io/v2alpha1
kind: Listener
metadata:
  name: {{ .Values.listenerName | quote }}
spec:
  routingKey: {{ .Values.routingKey | quote }}
  host: {{ .Values.listenerHost | quote }}
  port: {{ .Values.postgresPort }}
{{- end }}
