# role: app | data
role: app

# siteName: skupper-site-app | skupper-site-data
siteName: skupper-site-app

# linkAccessEnabled: true | false
# linkAccess: default | route | loadbalancer
linkAccessEnabled: false
linkAccess: default

connectorName: postgresql-connector
routingKey: postgresql
postgresSelector: app.kubernetes.io/name=postgresql
postgresPort: 5432

listenerName: postgresql-listener
listenerHost: postgresql
