{{- $dbsec := .Values.keycloak.postgres.credentialsSecret | required "keycloak.postgres.credentialsSecret is required" }}
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
spec:
  instances: 1
  db:
    vendor: postgres
    host: postgres-db
    usernameSecret:
      name: {{ $dbsec.name | quote }}
      key: {{ $dbsec.usernameKey | quote }}
    passwordSecret:
      name: {{ $dbsec.name | quote }}
      key: {{ $dbsec.passwordKey | quote }}
  http:
    httpEnabled: {{ .Values.keycloak.http.httpEnabled }}
    {{- with .Values.keycloak.http.tlsSecret }}
    tlsSecret: {{ . | quote }}
    {{- end }}
  ingress:
    enabled: {{ .Values.keycloak.ingress.enabled }}
    className: {{ .Values.keycloak.ingress.className | quote }}
    annotations:
      kubernetes.io/ingress.class: {{ .Values.keycloak.ingress.className | quote }}
    {{- with .Values.keycloak.ingress.tlsSecret }}
    tlsSecret: {{ . | quote }}
    {{- end }}
    path: /
    hosts:
      - {{ .Values.keycloak.hostname | quote }}
  {{- with .Values.keycloak.hostname }}
  hostname:
    hostname: {{ . | quote }}
  {{- end }}
  proxy:
    headers: xforwarded
