apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
spec:
  instances: 1
  db:
    vendor: postgres
    host: postgres-db
    usernameSecret:
      name: keycloak-db-secret
      key: username
    passwordSecret:
      name: keycloak-db-secret
      key: password
  http:
    httpEnabled: {{ .Values.keycloak.http.httpEnabled }}
    {{- with .Values.keycloak.http.tlsSecret }}
    tlsSecret: {{ . | quote }}
    {{- end }}
  ingress:
    enabled: {{ .Values.keycloak.ingress.enabled }}
    className: {{ .Values.keycloak.ingress.className | quote }}
    annotations:
      kubernetes.io/ingress.class: {{ .Values.keycloak.ingress.className | quote }}
    {{- with .Values.keycloak.ingress.tlsSecret }}
    tlsSecret: {{ . | quote }}
    {{- end }}
    path: /
    hosts:
      - {{ .Values.keycloak.hostname | quote }}
  {{- with .Values.keycloak.hostname }}
  hostname:
    hostname: {{ . | quote }}
  {{- end }}
  proxy:
    headers: xforwarded
